# Generated by Django 4.0 on 2021-12-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
    ]
