# Generated by Django 4.0 on 2021-12-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='solution',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviors.behavior')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviors.behavior')),
            ],
        ),
    ]
