# Generated by Django 4.0 on 2021-12-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0002_remove_behavior_problem_remove_behavior_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
