# Generated by Django 4.0 on 2021-12-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('behaviors', '0003_alter_behavior_created_at'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviors.behavior')),
                ('question', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
